{
    'name': 'Course Center',
    'version': '1.0',
    'summary': 'Course and enrollment management for Odoo 17',
    'description': 'Academic course center module for courses, groups, sessions, enrollments, attendance, and billing.',
    'category': 'Education',
    'author': 'Flavia Dervishaj',
    'website': 'https://github.com/flaviadervishaj/course-center-odoo',
    'depends': ['base'],

    'data': [
        'views/res_users_view.xml',
        'views/course_category_view.xml',
        'views/student_view.xml',
        'views/instructor_view.xml',
        'views/course_view.xml',
        'views/room_view.xml',
        'views/course_group_view.xml',
        'views/discount_rule_view.xml',
        'views/enrollment_view.xml',
        'views/course_session_view.xml',
        'views/assignment_view.xml',
        'views/attendance_view.xml',
        'views/submission_view.xml',
        'views/invoice_view.xml',
        'views/payment_view.xml',
        'views/certificate_view.xml',
        'views/menu.xml',
    ],

    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
