from . import res_users
from . import course_category
from . import student
from . import instructor
from . import course
from . import room
from . import course_group
from . import discount_rule
from . import enrollment
from . import course_session
from . import assignment
from . import attendance
from . import submission
from . import invoice
from . import payment
from . import certificate